# Generated by Django 6.0.6 on 2026-07-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendudukJenisKelamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kecamatan', models.CharField(max_length=100)),
                ('laki_laki', models.PositiveIntegerField(default=0)),
                ('perempuan', models.PositiveIntegerField(default=0)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penduduk_jenis_kelamin', to='dashboard.dataset')),
            ],
            options={
                'verbose_name': 'Penduduk Berdasarkan Jenis Kelamin',
                'verbose_name_plural': 'Penduduk Berdasarkan Jenis Kelamin',
                'db_table': 'penduduk_jenis_kelamin',
                'ordering': ['kecamatan'],
            },
        ),
        migrations.CreateModel(
            name='PendudukUsia6064',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_wilayah', models.CharField(max_length=20)),
                ('nama_wilayah', models.CharField(max_length=100)),
                ('usia', models.CharField(max_length=30)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penduduk_usia_6064', to='dashboard.dataset')),
            ],
            options={
                'verbose_name': 'Penduduk Usia 60-64 Tahun',
                'verbose_name_plural': 'Penduduk Usia 60-64 Tahun',
                'db_table': 'penduduk_usia_6064',
                'ordering': ['kode_wilayah'],
            },
        ),
        migrations.CreateModel(
            name='PenyandangDisabilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kecamatan', models.CharField(max_length=100)),
                ('jenis_disabilitas', models.CharField(max_length=150)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penyandang_disabilitas', to='dashboard.dataset')),
            ],
            options={
                'verbose_name': 'Penyandang Disabilitas',
                'verbose_name_plural': 'Penyandang Disabilitas',
                'db_table': 'penyandang_disabilitas',
                'ordering': ['kecamatan'],
            },
        ),
        migrations.CreateModel(
            name='PPKSDTKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kecamatan', models.CharField(max_length=100)),
                ('jumlah_ppks_mandiri', models.PositiveIntegerField(blank=True, default=0)),
                ('persentase_dtks', models.FloatField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppks_dtks', to='dashboard.dataset')),
            ],
            options={
                'verbose_name': 'PPKS dan DTKS',
                'verbose_name_plural': 'PPKS dan DTKS',
                'db_table': 'ppks_dtks',
                'ordering': ['kecamatan'],
            },
        ),
    ]
