# Generated by Django 6.0.6 on 2026-07-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pendudukjeniskelamin_pendudukusia6064_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyandangdisabilitas',
            name='jenis_disabilitas',
        ),
        migrations.RemoveField(
            model_name='penyandangdisabilitas',
            name='jumlah',
        ),
        migrations.AddField(
            model_name='penyandangdisabilitas',
            name='lainnya',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penyandangdisabilitas',
            name='tuna_fisik',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penyandangdisabilitas',
            name='tuna_fisik_dan_mental',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penyandangdisabilitas',
            name='tuna_mental_jiwa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penyandangdisabilitas',
            name='tuna_netra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penyandangdisabilitas',
            name='tuna_rungu_wicara',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
