# Generated by Django 6.0.6 on 2026-07-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_penyandangdisabilitas_jenis_disabilitas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisasiAPBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_belanja', models.CharField(max_length=100)),
                ('tahun_2021', models.BigIntegerField(default=0)),
                ('tahun_2022', models.BigIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisasi_apbd', to='dashboard.dataset')),
            ],
            options={
                'verbose_name': 'Realisasi APBD',
                'verbose_name_plural': 'Realisasi APBD',
                'db_table': 'realisasi_apbd',
                'ordering': ['id'],
            },
        ),
    ]
