# Generated by Django 6.0.6 on 2026-07-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_realisasiapbd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyekInvestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sektor', models.CharField(max_length=200)),
                ('pma', models.PositiveIntegerField(default=0)),
                ('pmdn', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyek_investasi', to='dashboard.dataset')),
            ],
            options={
                'verbose_name': 'Proyek Investasi PMA PMDN',
                'verbose_name_plural': 'Proyek Investasi PMA PMDN',
                'db_table': 'proyek_investasi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RealisasiPerizinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_izin', models.CharField(max_length=200)),
                ('izin_masuk', models.PositiveIntegerField(default=0)),
                ('izin_terbit', models.PositiveIntegerField(default=0)),
                ('izin_ditolak', models.PositiveIntegerField(default=0)),
                ('dalam_proses', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisasi_perizinan', to='dashboard.dataset')),
            ],
            options={
                'db_table': 'realisasi_perizinan',
                'ordering': ['id'],
            },
        ),
    ]
