# Generated by Django 6.0.6 on 2026-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_proyekinvestasi_realisasiperizinan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendudukjeniskelamin',
            name='kode_wilayah',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
